package exceptions

class ExitCommandCall : RuntimeException("была вызвана функция выхода из программы") {
}